[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/cheekybits/genny"

[[constraint]]
  name = "github.com/emirpasic/gods"
  version = "1.9.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gyuho/goraph"
  version = "2.0.0"
