// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package collect

type StringList []String

func (list *StringList) Append(t String) {
	*list = append(*list, t)
}

type ShaList []Sha

func (list *ShaList) Append(t Sha) {
	*list = append(*list, t)
}
