// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package collect

type StringSet map[String]bool

func (set *StringSet) Init() (s StringSet) {
	if s = *set; s == nil {
		s = make(StringSet)
		*set = s
	}
	return
}

func (set *StringSet) Add(val String) bool {
	if s := set.Init(); !s[val] {
		s[val] = true
		return true
	}
	return false
}

type ShaSet map[Sha]bool

func (set *ShaSet) Init() (s ShaSet) {
	if s = *set; s == nil {
		s = make(ShaSet)
		*set = s
	}
	return
}

func (set *ShaSet) Add(val Sha) bool {
	if s := set.Init(); !s[val] {
		s[val] = true
		return true
	}
	return false
}
