// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package file

type StringNodeList map[String]*StringNode

func (list StringNodeList) Add(node *StringNode) {
	if n, ok := list[node.Value]; ok {
		for _, child := range node.Children {
			n.Children.Add(child)
		}
	} else {
		list[node.Value] = node
	}
}
