// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package file

import "encoding/json"

type StringList = []String

type StringNode struct {
	Value String

	children StringNodeList
}

func NewStringNode(val String) *StringNode {
	return &StringNode{Value: val}
}

func ParseStringPath(path StringList) *StringNode {
	var node *StringNode
	if l := len(path); l > 0 {
		node = NewStringNode(path[0])
		if l > 1 {
			child := ParseStringPath(path[1:])
			node.Add(child)
		}
	}
	return node
}

var RootStringNode StringNode

func (n *StringNode) getChildren() StringNodeList {
	return n.children.init()
}

func (n *StringNode) Add(node *StringNode) {
	n.getChildren().add(node)
}

func (n StringNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.children)
}
